services:
    shortener-nginx:
        image: nginx:latest
        container_name: shortener-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./frontend/dist:/var/app/frontend/
        environment:
            TZ: Europe/Moscow
        networks:
            - app-network

    shortener-db:
        image: postgres:15
        container_name: shortener-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: shortener
            POSTGRES_PASSWORD: shortener
            POSTGRES_DB: shortener
            TZ: Europe/Moscow
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

    shortener-backend:
        container_name: shortener-backend
        working_dir: /var/app
        restart: unless-stopped
        build:
            context: ./backend
        ports:
            - '127.0.0.1:4200:4200'
        networks:
            - app-network
        volumes:
            - ./backend:/var/app/
            - /var/app/node_modules

volumes:
    db_data:

networks:
    app-network:
        driver: bridge