services:
    shortener-nginx:
        volumes:
            - ./.docker/nginx/prod.conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/prod.conf.d/site.conf:/etc/nginx/conf.d/site.conf

    shortener-backend:
        build:
            context: ./backend
            dockerfile: prod.Dockerfile
